CONSTRUCT {
  # Property
  ?Property_iri a aas:MultiLanguageProperty ;
    aassem:semanticId [
      a aas:Reference ;
      aasref:keys [
        a aas:Key ;
        aaskey:idType aaskeyt:IRI ;
        aaskey:value ?Property ;
      ] ;
    ] ;
    prov:wasDerivedFrom ?Property ;
    mas4ai:constructedByQuery "construct_multi-lang-property.rq" ;
  .
}
WHERE {
  ?Property a owl:DatatypeProperty ; #filter out reference properties
    rdfs:range rdf:langString .

  BIND(iri(concat( "http://mas4ai.eu/id/property/template/", struuid() )) as ?Property_iri)
}