CONSTRUCT {
  # Property
  ?Property_iri a aas:Property ;
    aasprop:valueType ?dataType ;
    aassem:semanticId [
      a aas:Reference ;
      aasref:keys [
        a aas:Key ;
        aaskey:idType aaskeyt:IRI ;
        aaskey:value ?Property ;
      ] ;
    ] ;
    prov:wasDerivedFrom ?Property ;
  .
}
WHERE {
  ?Property a owl:DatatypeProperty ; #filter out reference properties
    rdfs:range ?dataType .

  BIND(iri(concat( "http://mas4ai.eu/id/property/template/", struuid() )) as ?Property_iri)
}