PREFIX prov:    <http://www.w3.org/ns/prov#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX mas4ai:  <http://example.org/MAS4AI_GenericModel#>
PREFIX aas:     <https://admin-shell.io/aas/3/0/RC01/>
PREFIX aasenv:  <https://admin-shell.io/aas/3/0/RC01/AssetAdministrationShellEnvironment/>
PREFIX aasaas:  <https://admin-shell.io/aas/3/0/RC01/AssetAdministrationShell/>
PREFIX aassm:   <https://admin-shell.io/aas/3/0/RC01/Submodel/>
PREFIX aassmc:  <https://admin-shell.io/aas/3/0/RC01/SubmodelElementCollection/>
PREFIX aasrefer: <https://admin-shell.io/aas/3/0/RC01/Referable/>
PREFIX aasrel:  <https://admin-shell.io/aas/3/0/RC01/RelationshipElement/>
PREFIX aasdata: <https://admin-shell.io/aas/3/0/RC01/HasDataSpecification/>
PREFIX aasprop: <https://admin-shell.io/aas/3/0/RC01/Property/>
PREFIX aasrange: <https://admin-shell.io/aas/3/0/RC01/Range/>
PREFIX aassem:  <https://admin-shell.io/aas/3/0/RC01/HasSemantics/>
PREFIX aasref:  <https://admin-shell.io/aas/3/0/RC01/Reference/>
PREFIX aaskey:  <https://admin-shell.io/aas/3/0/RC01/Key/>
PREFIX aasida:  <https://admin-shell.io/aas/3/0/RC01/Identifiable/>
PREFIX aaside:  <https://admin-shell.io/aas/3/0/RC01/Identifier/>
PREFIX aaskeyt: <https://admin-shell.io/aas/3/0/RC01/KeyType/>
PREFIX aaskind: <https://admin-shell.io/aas/3/0/RC01/HasKind/>
PREFIX aasmod:  <https://admin-shell.io/aas/3/0/RC01/ModelingKind/>